[project]
authors = [
    { name = "Slava Chaunin", email = "67190162+Ssslakter@users.noreply.github.com" },
]
dependencies = [
    "torch>=2.7",
    "numpy",
    "datasets",
    "matplotlib",
    "transformers",
    "jupyter",
    "tqdm",
    "trackio",
    "torchvision",
    "hydra-core",
    "wandb"
]
name = "trainer-tools"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
trainer-tools = { path = ".", editable = true }


[tool.pixi.tasks]


[tool.black]
line-length = 120
