[project]
authors = [
    { name = "Slava Chaunin", email = "67190162+Ssslakter@users.noreply.github.com" },
]
dependencies = [
    "torch>=2.7",
    "numpy",
    "matplotlib",
    "tqdm",
    "trackio",
    "hydra-core",
    "wandb",
]
name = "trainer-tools"
readme = "README.md"
requires-python = ">= 3.11"
version = "0.1.2"
license = { file = "LICENSE" }
keywords = ["pytorch", "deep-learning", "training", "trainer"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]


[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
trainer-tools = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[tool.pixi.tasks]

[tool.black]
line-length = 120

[dependency-groups]
dev = ["jupyter", "pytest", "memray", "build", "twine"]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-autorefs"
]